# ==============================================================================
# ==============================================================================
# ============================== Module Saving ================================
# ==============================================================================
# ==============================================================================

"""
    Module: Saving

Author: Michelangelo Dondi
Date: 02-10-2023
Description:
    Dedicated to saving plots generated by the Circuit Visualization Tool.
    This module simplifies the saving process by providing a single function to call.

Version: 2.0
License: MIT License

Exported functions:
- `save_current_plot()`: Saves the current plot into an "Images" directory with a timestamped filename.
"""
module Saving

    # Invoke this function to export the save_current_plot function
    export save_current_plot 

    # ==============================================================================
    # =========================== Required Packages ===============================
    # ==============================================================================

        using Plots # For saving plots
        using Dates # For generating timestamped filenames
    
    # ==============================================================================
    # =========================== Exported functions ===============================
    # ==============================================================================

    """
        save_current_plot() -> nothing

    Saves the current plot into an "Images" directory with a timestamped filename.

    Parameters:
    - None

    Returns:
    - nothing
    """
    function save_current_plot()
        # Determine paths
        project_dir = joinpath(@__DIR__, "..")   # Project root directory
        images_dir = _ensure_images_directory(project_dir)
        
        # Generate a timestamped filename
        filename = _generate_filename()
        filepath = joinpath(images_dir, filename)
        
        # Save the plot and provide feedback to user
        Plots.savefig(filepath)
        println("Circuit plot saved as '$filepath'.")
    end

    # ==============================================================================
    # =========================== Internal functions ===============================
    # ==============================================================================

    """
        ensure_images_directory(base_dir::String) -> String

    Ensures that an "Images" directory exists within the specified base directory.
    Returns the path to the "Images" directory.

    Parameters:
    - base_dir: The base directory to check for the existence of an "Images" directory.

    Returns:
    - The path to the "Images" directory.
    """
    function _ensure_images_directory(base_dir::String)
        images_path = joinpath(base_dir, "Images")
        if !isdir(images_path)
            mkdir(images_path)
        end
        return images_path
    end    

    """
        generate_filename() -> String

    Generates a timestamped filename for saving plots.

    Parameters:
    - None
        
    Returns:
    - The generated filename.
    """
    function _generate_filename()
        formatted_date = Dates.format(Dates.now(), "YYYY_MM_DD_HH_MM_SS")
        return "circuit_plot_$(formatted_date).png"
    end

end